"use client";

import { useState, useRef, useEffect } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import {
  chatWithGeneratedPersona,
  fetchGeneratedPersona,
  GeneratedPersona,
  DecisionTrace,
} from "@/lib/api";

interface Message {
  role: "user" | "persona";
  text: string;
  trace?: DecisionTrace | null;
}

const DEFAULT_QUESTIONS = [
  "Walk me through how you decide whether to try a new product or service.",
  "What's something you've changed your mind about in the last few years?",
  "When you're choosing between options, what wins — price, quality, or trust?",
  "What would make you switch away from a brand you currently rely on?",
  "Tell me about a recent purchase you regret and why.",
];

export default function GeneratedChatPage() {
  const params = useParams<{ id: string }>();
  const id = params?.id ?? "";

  const [persona, setPersona] = useState<GeneratedPersona | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [resumedFrom, setResumedFrom] = useState<string | null>(null);
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!id) return;
    fetchGeneratedPersona(id)
      .then(setPersona)
      .catch((e: unknown) =>
        setError(e instanceof Error ? e.message : "Could not load persona"),
      );
  }, [id]);

  // Rehydrate from active session (if any) on mount. Same-origin proxy:
  // /api/generated/[id]/chats/active. Silent on failure — empty state is fine.
  useEffect(() => {
    if (!id) return;
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch(`/api/generated/${id}/chats/active`, {
          cache: "no-store",
        });
        if (!res.ok) return;
        const data = (await res.json()) as {
          session_id: string | null;
          messages: { role: string; content: string; created_at: string | null }[];
          last_message_at?: string | null;
        };
        if (cancelled) return;
        if (data.session_id && data.messages?.length) {
          const hydrated: Message[] = data.messages.map((m) => ({
            role: m.role === "persona" ? "persona" : "user",
            text: m.content,
          }));
          setMessages(hydrated);
          // Resumed-from timeago label.
          const ts = data.last_message_at;
          if (ts) {
            const diffMs = Date.now() - new Date(ts).getTime();
            const mins = Math.max(1, Math.round(diffMs / 60000));
            setResumedFrom(
              mins < 60
                ? `${mins}m ago`
                : `${Math.round(mins / 60)}h ago`,
            );
          } else {
            setResumedFrom("earlier");
          }
        }
      } catch {
        // ignore — start with empty state
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [id]);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, loading]);

  const send = async (text: string) => {
    if (!text.trim() || loading) return;
    setInput("");
    setError("");
    setMessages((prev) => [...prev, { role: "user", text }]);
    setLoading(true);

    try {
      const res = await chatWithGeneratedPersona(id, text, true);
      setMessages((prev) => [
        ...prev,
        { role: "persona", text: res.reply, trace: res.decision_trace },
      ]);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Request failed");
    } finally {
      setLoading(false);
    }
  };

  const da = persona?.demographic_anchor;
  const di = persona?.derived_insights;
  const firstName =
    persona?.narrative?.display_name || da?.name?.split(" ")[0] || "this persona";
  const personaName =
    persona?.narrative?.display_name || da?.name || "persona";

  function downloadConversation() {
    if (messages.length === 0) return;
    const date = new Date().toISOString().slice(0, 10);
    const header =
      `# Conversation with ${personaName}\n\n` +
      `Exported ${date}\nGenerated by The Mind — Simulatte\n\n` +
      `> ⚠️ This is a conversation with a synthetic persona generated by The Mind.\n` +
      `> ${personaName} is not a real person. Their views are simulated and should not\n` +
      `> be attributed to any real individual.\n\n` +
      `---\n\n`;
    const body = messages.map((m) => {
      const who = m.role === "user" ? "You" : personaName;
      return `**${who}:**\n\n${m.text}\n`;
    }).join("\n");
    const text = header + body;
    const blob = new Blob([text], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `chat-${personaName.toLowerCase().replace(/\s+/g, "-")}-${date}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="min-h-screen flex flex-col max-w-3xl mx-auto px-4 py-8">
      {/* Back nav */}
      <div className="flex items-center justify-between mb-8 gap-3">
        <Link
          href={`/persona/${id}`}
          className="text-[11px] font-semibold tracking-widest uppercase text-static hover:text-parchment/50 transition-colors inline-block"
        >
          ← Back to profile
        </Link>
        {messages.length >= 2 && (
          <button
            type="button"
            onClick={downloadConversation}
            className="text-[11px] font-mono uppercase tracking-widest text-signal hover:text-parchment transition-colors"
          >
            Download conversation
          </button>
        )}
      </div>

      {/* Persona header */}
      {persona && da && di && (
        <div className="border border-parchment/10 p-5 mb-8">
          <p className="text-[11px] font-semibold tracking-widest uppercase text-signal mb-1">
            {da.life_stage.replace(/_/g, " ")}
          </p>
          <h1 className="font-condensed font-bold text-3xl text-parchment leading-none">
            {da.name}
          </h1>
          <p className="text-static text-sm mt-1">
            {da.age} · {da.location.city}, {da.location.country}
          </p>
          {persona.narrative.third_person && (
            <p className="text-parchment/65 text-sm mt-2">
              {persona.narrative.third_person}
            </p>
          )}
          <div className="flex gap-3 mt-3 flex-wrap">
            <span className="font-mono text-[10px] text-static">
              {di.decision_style} decision style
            </span>
            <span className="text-parchment/20">·</span>
            <span className="font-mono text-[10px] text-static">
              consistency {di.consistency_score}
            </span>
          </div>
        </div>
      )}

      {/* Suggested questions */}
      {messages.length === 0 && !loading && (
        <div className="mb-6">
          <p className="text-[11px] font-semibold tracking-widest uppercase text-static mb-3">
            Suggested questions
          </p>
          <div className="space-y-2">
            {DEFAULT_QUESTIONS.map((q) => (
              <button
                key={q}
                onClick={() => send(q)}
                className="block w-full text-left border border-parchment/10 px-4 py-3 text-sm text-parchment/70 hover:text-parchment hover:border-parchment/25 transition-colors"
              >
                {q}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Message thread */}
      <div className="flex-1 space-y-6 mb-6">
        {resumedFrom && messages.length > 0 && (
          <p className="text-[10px] font-mono text-static uppercase tracking-widest">
            Resumed from {resumedFrom}
          </p>
        )}
        {messages.map((msg, idx) => (
          <div key={idx}>
            {msg.role === "user" ? (
              <div className="flex justify-end">
                <div className="max-w-lg border border-parchment/15 px-4 py-3 text-sm text-parchment/85">
                  {msg.text}
                </div>
              </div>
            ) : (
              <div className="border-l-2 border-signal pl-4">
                <p className="text-[10px] font-mono text-static mb-2 uppercase tracking-widest">
                  {firstName}
                </p>
                <p className="text-parchment text-sm leading-relaxed whitespace-pre-wrap">
                  {msg.text}
                </p>
              </div>
            )}
          </div>
        ))}

        {loading && (
          <div className="border-l-2 border-signal/40 pl-4">
            <p className="text-[10px] font-mono text-static mb-2 uppercase tracking-widest">
              {firstName}
            </p>
            <div className="flex gap-1 items-center h-5">
              {[0, 1, 2].map((i) => (
                <span
                  key={i}
                  className="inline-block w-1 h-1 bg-signal/60 animate-pulse"
                  style={{ animationDelay: `${i * 150}ms` }}
                />
              ))}
            </div>
          </div>
        )}

        {error && (
          <p className="font-mono text-[11px] text-static border border-parchment/10 px-3 py-2">
            {error}
          </p>
        )}

        <div ref={bottomRef} />
      </div>

      {/* Input */}
      <div className="border border-parchment/15 flex">
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && !e.shiftKey && send(input)}
          placeholder={`Ask ${firstName} anything…`}
          disabled={loading || !persona}
          className="flex-1 bg-transparent px-4 py-3 text-sm text-parchment placeholder:text-static/50 outline-none disabled:opacity-50"
        />
        <button
          onClick={() => send(input)}
          disabled={loading || !input.trim() || !persona}
          className="px-4 py-3 text-[11px] font-semibold tracking-widest uppercase text-void bg-signal hover:bg-signal/90 transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
        >
          Send
        </button>
      </div>

    </div>
  );
}
