from __future__ import annotations

from src.taxonomy.base_taxonomy import AttributeDefinition


def _domain_attr_definitions(
    attrs: list[AttributeDefinition],
) -> list[AttributeDefinition]:
    # `AttributeDefinition` from Codex doesn’t define `is_domain_specific`, but
    # Goose’s filler uses it to decide the fill-order. Mark these objects
    # explicitly.
    for a in attrs:
        setattr(a, "is_domain_specific", True)

        # `AttributeFiller` falls back via `attr_def.population_prior.get(...)`.
        # The Codex taxonomy stores priors as floats, but for domain templates
        # we normalize them to a small dict contract.
        pp = getattr(a, "population_prior", None)
        if isinstance(pp, (int, float)):
            v = float(pp)
            if v > 0.66:
                label = "high"
            elif v > 0.33:
                label = "medium"
            else:
                label = "low"
            setattr(a, "population_prior", {"value": v, "label": label})
    return attrs


CPG_DOMAIN_ATTRIBUTES: list[AttributeDefinition] = _domain_attr_definitions(
    [
        AttributeDefinition(
            name="private_label_acceptance",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.37,
            description="Willingness to buy store-brand alternatives over national brands.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="national_brand_attachment",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.46,
            description="Emotional/identity attachment to established national brands (vs rotating brands).",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="pack_size_preference",
            category="values",
            attr_type="categorical",
            options=["single_use", "standard", "bulk"],
            population_prior=0.0,
            description="Preference for pack sizes that match their usage rate and storage capacity.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="online_grocery_adoption",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.41,
            description="Tendency to shop for grocery/essentials via online ordering/delivery.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="modern_trade_preference",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.44,
            description="Preference for modern retail formats (supermarkets/large chains) over local formats.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="kirana_preference",
            category="social",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.46,
            description="Preference for neighborhood/local stores (kirana) often tied to familiarity and relationship.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="coupon_redemption_rate",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.36,
            description="Likelihood of using coupons/discount codes during CPG purchases.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="bundle_offer_responsiveness",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.42,
            description="Responsiveness to bundle pricing (multi-pack deals) as a reason to buy.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="cashback_sensitivity",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.33,
            description="Sensitivity to cashback/instant refunds as a purchase trigger.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="personal_care_involvement",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.48,
            description="How much attention they allocate to personal-care product choice (skin/hair outcomes).",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="food_health_involvement",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.45,
            description="Degree to which health considerations shape food choices (nutrition, ingredients, impact).",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="household_product_involvement",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.41,
            description="Attention level toward household goods (cleaning, detergents, hygiene, safety).",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="stockpiling_tendency",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.34,
            description="Tendency to buy extra quantities when prices are favorable or inventory seems limited.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="pantry_loading_frequency",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.36,
            description="How often they replenish pantry/household staples ahead of need.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="subscription_box_openness",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.28,
            description="Openness to recurring replenishment/shopping subscriptions for consumables.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="ingredient_scrutiny",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.46,
            description="How carefully they evaluate ingredients and composition before choosing.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="nutritional_label_check",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.39,
            description="Likelihood of checking nutrition facts/label claims for foods or beverages.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="country_of_origin_sensitivity",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.29,
            description="Sensitivity to country-of-origin information and related trust assumptions.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="gifting_frequency",
            category="social",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.27,
            description="Frequency of using CPG items as gifts (food, personal-care, household goods).",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="occasion_driven_purchase",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.38,
            description="Purchases triggered by events/occasions rather than routine replenishment.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="impulse_at_checkout",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.34,
            description="Tendency to add extra items during checkout due to visibility and convenience.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="new_product_trial_rate",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.33,
            description="Likelihood of trying new brands/products within a familiar category.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="category_exploration_width",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.41,
            description="How many distinct options/brands they consider during a category purchase.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="sustainability_claim_weighting",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.35,
            description="How strongly sustainability-related claims affect their purchase decision.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="ethical_certification_trust",
            category="social",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.31,
            description="Trust in certifications/ethical badges (e.g., cruelty-free, fair trade) as decision inputs.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="price_grade_awareness",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.43,
            description="Awareness of different price tiers/grades within a category and what they imply.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="discount_cycle_planning",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.36,
            description="Plans pantry/consumable purchases around predicted discount cycles or promotions.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="trial_sampling_channel_preference",
            category="social",
            attr_type="categorical",
            options=["in_store_samples", "online_reviews", "friends_recommendations"],
            population_prior=0.0,
            description="Preferred way to evaluate products before committing (samples, reviews, social recs).",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="refill_vs_replacement_preference",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.33,
            description="Preference for refills/replacement systems (e.g., refill pouches) over buying new units.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="reorder_reminder_dependence",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.44,
            description="Dependence on reminders/apps/notifications to remember replenishment.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="out_of_stock_switching_behavior",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.38,
            description="How likely they are to switch brands/categories when their preferred item is out of stock.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="brand_safety_concern",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.39,
            description="Concern about brand-level safety issues, recalls, or risk reputation.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="allergy_safety_priority",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.41,
            description="Priority given to avoiding allergens or irritants in consumables and personal care.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="family_health_responsibility",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.47,
            description="How strongly family/household health drives what they buy (especially food and household goods).",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="convenience_pack_preference",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.48,
            description="Preference for packs that reduce hassle (ready-to-use, portioned, easy-to-store sizes).",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="free_shipping_threshold_sensitivity",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.42,
            description="How much shipping cost affects their decision to bundle/meet minimum order thresholds.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="return_refund_expectation",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.3,
            description="Expectation that they can return/refund if the product is not satisfactory.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="complaint_engagement_level",
            category="social",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.22,
            description="How likely they are to engage with customer service or file complaints after poor CPG experiences.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="review_writing_motivation",
            category="social",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.28,
            description="Motivation to write reviews/ratings to influence others after product usage.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="in_app_promo_engagement",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.33,
            description="Engagement with in-app promotions (wallet offers, gamified discounts, personalized coupons).",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="loyalty_program_enrollment_drive",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.24,
            description="Drive to enroll in loyalty programs for points, member-only pricing, or perks.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="loyalty_program_benefit_expectation",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.27,
            description="Expectation that loyalty programs meaningfully reduce cost or improve product access.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="size_variant_openness",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.36,
            description="Openness to switching between size/variant SKUs within the same brand/category.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="taste_preference_adaptability",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.34,
            description="Adaptability to taste/texture variations (e.g., flavor substitutions or formula updates).",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="brand_story_resonance",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.3,
            description="How much brand story/heritage influences choice relative to performance and price.",
            is_anchor=False,
        ),
    ]
)


__all__ = ["CPG_DOMAIN_ATTRIBUTES"]
