from __future__ import annotations

from src.taxonomy.base_taxonomy import AttributeDefinition


def _domain_attr_definitions(
    attrs: list[AttributeDefinition],
) -> list[AttributeDefinition]:
    # `AttributeDefinition` from Codex doesn't define `is_domain_specific`, but
    # Goose's filler uses it to decide the fill-order. Mark these objects
    # explicitly.
    for a in attrs:
        setattr(a, "is_domain_specific", True)

        # `AttributeFiller` falls back via `attr_def.population_prior.get(...)`.
        # The Codex taxonomy stores priors as floats, but for domain templates
        # we normalize them to a small dict contract.
        pp = getattr(a, "population_prior", None)
        if isinstance(pp, (int, float)):
            v = float(pp)
            if v > 0.66:
                label = "high"
            elif v > 0.33:
                label = "medium"
            else:
                label = "low"
            setattr(a, "population_prior", {"value": v, "label": label})
    return attrs


ECOMMERCE_DOMAIN_ATTRIBUTES: list[AttributeDefinition] = _domain_attr_definitions(
    [
        # --- Required attributes ---
        AttributeDefinition(
            name="return_friction_tolerance",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.41,
            description="Willingness to navigate multi-step return or refund processes without abandoning the merchant.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="discovery_mode",
            category="lifestyle",
            attr_type="categorical",
            options=["search_led", "browse", "social", "algo_fed"],
            population_prior=0.0,
            description="Primary channel through which they find new products when not on a specific mission.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="marketplace_trust_variance",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.52,
            description="Degree to which trust differs between third-party marketplace sellers and official brand storefronts.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="cart_abandonment_propensity",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.48,
            description="Tendency to build carts without completing purchase, often using the cart as a wishlist or comparison tool.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="review_dependence",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.61,
            description="Reliance on user-generated reviews and ratings as a prerequisite before completing a purchase decision.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="delivery_speed_sensitivity",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.44,
            description="Willingness to pay a premium or switch retailers to secure faster delivery times.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="subscription_model_openness",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.35,
            description="Comfort with auto-renewing subscription commerce arrangements for regular replenishment or curated boxes.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="personalisation_acceptance",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.46,
            description="Comfort with algorithmic personalisation of product feeds and recommendations in exchange for relevance.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="live_commerce_engagement",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.22,
            description="Engagement with live-stream shopping formats where hosts demo and sell products in real time.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="cross_border_shopping_willingness",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.33,
            description="Comfort purchasing from international sellers despite longer delivery windows and customs uncertainty.",
            is_anchor=False,
        ),
        # --- Additional attributes ---
        AttributeDefinition(
            name="price_comparison_depth",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.57,
            description="How many competing prices or sites they check before committing to an online purchase.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="checkout_friction_tolerance",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.38,
            description="Tolerance for multi-step checkout flows, account creation requirements, and address verification steps.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="free_shipping_threshold_response",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.55,
            description="Tendency to add extra items to a cart specifically to meet a free-shipping minimum threshold.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="flash_sale_responsiveness",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.43,
            description="Responsiveness to time-limited flash sales, countdown timers, and scarcity-framed discount events.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="product_image_reliance",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.62,
            description="Degree to which product photography quality and variety directly influences purchase confidence.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="size_fit_anxiety",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.51,
            description="Anxiety about ordering the wrong size or fit when buying apparel or footwear online.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="loyalty_points_motivation",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.36,
            description="Motivation to concentrate spending on one platform to accumulate loyalty points or cashback rewards.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="wishlist_usage_frequency",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.42,
            description="How frequently they use wishlists or save-for-later features as part of their purchase journey.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="social_sharing_of_purchases",
            category="social",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.27,
            description="Likelihood of sharing, posting, or reviewing a purchase on social media after receipt.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="unboxing_experience_value",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.31,
            description="Weight placed on packaging quality and unboxing experience as part of perceived product value.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="seller_rating_threshold",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.58,
            description="Minimum seller or store rating they require before trusting a marketplace listing enough to purchase.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="product_question_engagement",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.34,
            description="Tendency to read or submit Q&A sections on product pages to resolve pre-purchase uncertainties.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="augmented_reality_try_on_openness",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.28,
            description="Openness to using AR try-on or virtual placement tools to reduce uncertainty before buying.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="mobile_shopping_preference",
            category="lifestyle",
            attr_type="categorical",
            options=["mobile_first", "desktop_first", "no_preference"],
            population_prior=0.0,
            description="Preferred device context for browsing and completing online purchases.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="same_day_delivery_premium_ceiling",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.29,
            description="How large a delivery surcharge they will accept in exchange for same-day or express fulfilment.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="influencer_product_purchase_rate",
            category="social",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.32,
            description="Rate at which influencer content or creator affiliate links convert into actual purchases.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="bundle_deal_responsiveness",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.45,
            description="Likelihood of upgrading or adding items when presented with a discounted product bundle.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="counterfeit_concern",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.49,
            description="Level of concern about receiving counterfeit or inauthentic products when buying from third-party sellers.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="sustainability_label_weighting",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.37,
            description="Weight placed on eco-friendly labels, sustainable packaging claims, and carbon-neutral shipping options.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="repeat_purchase_inertia",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.53,
            description="Tendency to reorder the same product from the same seller without re-evaluating alternatives.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="d2c_brand_preference",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.38,
            description="Preference for buying directly from brand-owned stores over aggregator marketplaces.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="payment_method_breadth",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.47,
            description="Comfort using a wide variety of payment methods including BNPL, digital wallets, and crypto.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="bnpl_adoption",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.31,
            description="Adoption of buy-now-pay-later financing options to spread purchase cost over instalments.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="post_purchase_tracking_engagement",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.56,
            description="Frequency of checking order tracking and delivery status updates after placing an order.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="gifting_purchase_frequency",
            category="social",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.34,
            description="Frequency of purchasing products online specifically intended as gifts for others.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="private_label_ecom_acceptance",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.40,
            description="Willingness to purchase platform private-label products (e.g., marketplace basics) over branded equivalents.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="deal_aggregator_usage",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.33,
            description="Frequency of consulting deal aggregator sites or browser extensions to find lower prices before checkout.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="customer_service_expectation",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.50,
            description="Expectation of responsive, frictionless customer service as a baseline condition for shopping with a retailer.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="resale_market_openness",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.30,
            description="Openness to purchasing second-hand, refurbished, or pre-owned goods through online resale platforms.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="category_purchase_breadth",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.44,
            description="Number of distinct product categories they regularly buy online, reflecting platform consolidation tendency.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="notification_opt_in_rate",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.39,
            description="Tendency to opt into push notifications, email alerts, and price-drop reminders from ecommerce platforms.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="impulse_purchase_susceptibility",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.42,
            description="Susceptibility to making unplanned purchases triggered by recommendation engines or limited-time prompts.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="review_writing_propensity",
            category="social",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.26,
            description="Likelihood of writing a product review after purchase, contributing to the review ecosystem they rely on.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="brand_switching_ease",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.43,
            description="Ease with which they switch to a new brand online when a price or quality incentive presents itself.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="omnichannel_research_pattern",
            category="decision_making",
            attr_type="categorical",
            options=["online_research_online_buy", "offline_research_online_buy", "online_research_offline_buy", "fully_online"],
            population_prior=0.0,
            description="Pattern describing where research occurs and where the final purchase is made across channels.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="data_privacy_concern_ecom",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.47,
            description="Concern about how ecommerce platforms collect and use personal browsing and purchase data.",
            is_anchor=False,
        ),
    ]
)


__all__ = ["ECOMMERCE_DOMAIN_ATTRIBUTES"]
