from __future__ import annotations

from src.taxonomy.base_taxonomy import AttributeDefinition


def _domain_attr_definitions(
    attrs: list[AttributeDefinition],
) -> list[AttributeDefinition]:
    # `AttributeDefinition` from Codex doesn't define `is_domain_specific`, but
    # Goose's filler uses it to decide the fill-order. Mark these objects
    # explicitly.
    for a in attrs:
        setattr(a, "is_domain_specific", True)

        # `AttributeFiller` falls back via `attr_def.population_prior.get(...)`.
        # The Codex taxonomy stores priors as floats, but for domain templates
        # we normalize them to a small dict contract.
        pp = getattr(a, "population_prior", None)
        if isinstance(pp, (int, float)):
            v = float(pp)
            if v > 0.66:
                label = "high"
            elif v > 0.33:
                label = "medium"
            else:
                label = "low"
            setattr(a, "population_prior", {"value": v, "label": label})
    return attrs


EDUCATION_DOMAIN_ATTRIBUTES: list[AttributeDefinition] = _domain_attr_definitions(
    [
        # --- Required attributes ---
        AttributeDefinition(
            name="credential_credibility_bias",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.55,
            description="Preference for accredited or institutionally recognised credentials over alternative or bootcamp-style certifications.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="self_directed_study_capacity",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.44,
            description="Ability to learn effectively without external structure, deadlines, or instructor-led guidance.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="parent_vs_self_buyer_role",
            category="decision_making",
            attr_type="categorical",
            options=["self_decides", "parent_decides", "joint_decision", "guardian_decides"],
            population_prior=0.0,
            description="Whether the educational purchase decision is made independently by the learner or driven by a parent or guardian.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="completion_rate_tendency",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.42,
            description="Historical tendency to finish enrolled courses rather than dropping out after initial engagement.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="peer_learning_preference",
            category="social",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.48,
            description="Value placed on cohort-based and peer-collaborative learning versus solitary self-study.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="live_vs_async_preference",
            category="lifestyle",
            attr_type="categorical",
            options=["live_only", "async_only", "mixed", "no_preference"],
            population_prior=0.0,
            description="Preference for synchronous live instruction versus on-demand asynchronous content consumption.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="price_elasticity_education",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.52,
            description="Price sensitivity specific to educational products — how strongly cost reduces willingness to enroll.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="career_outcome_focus",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.58,
            description="Degree to which expected job placement rates, salary uplift, or career advancement drive educational purchasing choices.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="brand_prestige_in_education",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.50,
            description="Value placed on institutional brand name and prestige as a signal of quality and social recognition.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="continuous_learning_orientation",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.47,
            description="Intrinsic motivation to keep learning and upskilling beyond the completion of formal education.",
            is_anchor=False,
        ),
        # --- Additional attributes ---
        AttributeDefinition(
            name="free_trial_course_dependency",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.46,
            description="Reliance on free trial lessons or sample content before committing to a paid enrolment.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="instructor_reputation_weight",
            category="social",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.54,
            description="Degree to which the instructor's professional reputation and reviews drive course selection.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="learning_format_preference",
            category="lifestyle",
            attr_type="categorical",
            options=["video_lecture", "text_based", "project_based", "interactive_exercises", "blended"],
            population_prior=0.0,
            description="Preferred instructional format that best matches their learning style and context of use.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="mobile_learning_comfort",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.43,
            description="Comfort consuming educational content on a mobile device during commutes or fragmented time slots.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="certification_sharability_value",
            category="social",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.49,
            description="Value placed on receiving a shareable certificate or digital badge that can be displayed on LinkedIn or a resume.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="employer_sponsorship_reliance",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.34,
            description="Tendency to only pursue learning when employer funding or reimbursement is available.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="study_schedule_rigidity",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.40,
            description="Preference for a fixed structured study timetable over flexible self-paced learning.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="assessment_anxiety",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.45,
            description="Level of anxiety triggered by formal assessments, quizzes, or examinations within a course.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="community_forum_engagement",
            category="social",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.33,
            description="Likelihood of engaging in course discussion forums, study groups, or peer-help channels.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="prerequisite_tolerance",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.38,
            description="Willingness to complete prerequisite courses or assessments before accessing advanced material.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="corporate_training_receptiveness",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.44,
            description="Openness to employer-mandated or corporate-issued training programmes versus self-chosen learning paths.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="skill_gap_self_awareness",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.50,
            description="Accuracy of their self-assessment of current skill gaps relative to their career or personal goals.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="gamification_responsiveness",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.39,
            description="Motivation boost derived from gamified elements such as streaks, leaderboards, and points systems.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="short_form_content_preference",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.51,
            description="Preference for micro-lessons and bite-sized modules over long-form structured courses.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="feedback_frequency_expectation",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.46,
            description="How frequently they expect personalised feedback or instructor interaction to feel the course delivers value.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="ai_tutor_openness",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.37,
            description="Openness to receiving instruction, feedback, or tutoring from AI-powered tools rather than human instructors.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="refund_policy_importance",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.43,
            description="Degree to which a clear refund or money-back guarantee reduces enrolment risk and increases conversion.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="language_of_instruction_flexibility",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.41,
            description="Willingness to learn in a non-native language if content quality or credential value is sufficiently high.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="peer_benchmark_sensitivity",
            category="social",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.48,
            description="Sensitivity to information about peer progress or cohort performance relative to their own.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="hands_on_project_need",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.55,
            description="Need for practical projects or portfolio-building exercises as a core component of the learning experience.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="institutional_accreditation_gate",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.52,
            description="Whether institutional accreditation is a hard filter that eliminates non-accredited options from consideration.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="time_to_skill_urgency",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.49,
            description="How urgently they need to acquire a skill, driving preference for intensive accelerated formats over leisurely programmes.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="passive_vs_active_learning_orientation",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.46,
            description="Tendency toward active recall and practice exercises versus passive content consumption like watching videos.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="alumni_network_value",
            category="social",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.38,
            description="Weight placed on access to an alumni network or professional community as part of the programme's value proposition.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="multi_course_platform_loyalty",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.35,
            description="Tendency to take multiple courses from the same platform rather than mixing providers per learning goal.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="offline_access_requirement",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.32,
            description="Need to download and access course materials offline due to unreliable internet connectivity or travel.",
            is_anchor=False,
        ),
    ]
)


__all__ = ["EDUCATION_DOMAIN_ATTRIBUTES"]
