from __future__ import annotations

from src.taxonomy.base_taxonomy import AttributeDefinition


def _domain_attr_definitions(
    attrs: list[AttributeDefinition],
) -> list[AttributeDefinition]:
    # Mark all attributes as domain-specific so the filler knows to treat
    # them as supplemental, and normalise population_prior floats to the
    # dict contract used by AttributeFiller.
    for a in attrs:
        setattr(a, "is_domain_specific", True)

        pp = getattr(a, "population_prior", None)
        if isinstance(pp, (int, float)):
            v = float(pp)
            if v > 0.66:
                label = "high"
            elif v > 0.33:
                label = "medium"
            else:
                label = "low"
            setattr(a, "population_prior", {"value": v, "label": label})
    return attrs


FINANCIAL_SERVICES_DOMAIN_ATTRIBUTES: list[AttributeDefinition] = _domain_attr_definitions(
    [
        # ── core financial attitudes ──────────────────────────────────────
        AttributeDefinition(
            name="credit_risk_tolerance",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.42,
            description="Willingness to take on debt or leverage to achieve financial or lifestyle goals.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="regulatory_trust",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.48,
            description="Trust in financial regulatory bodies and confidence that compliance frameworks protect consumers.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="financial_advisor_dependence",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.44,
            description="Reliance on human financial advisors rather than self-directed research and investing.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="digital_banking_comfort",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.55,
            description="Comfort managing finances entirely through apps with no branch or in-person access.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="investment_horizon",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.50,
            description="Tendency toward long-term investment planning (1.0) versus short-term speculative trading (0.0).",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="insurance_perceived_value",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.46,
            description="Belief that insurance products deliver fair value relative to their premium cost.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="open_banking_willingness",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.35,
            description="Comfort sharing financial data across third-party platforms via open banking APIs.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="crypto_openness",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.30,
            description="Interest in or willingness to hold and transact with cryptocurrency assets.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="fee_sensitivity_financial",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.58,
            description="Price sensitivity specific to financial product fees, including management fees, transaction costs, and account charges.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="financial_literacy_self_rating",
            category="identity",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.47,
            description="Self-assessed confidence in understanding financial concepts, products, and markets.",
            is_anchor=False,
        ),
        # ── banking behaviour ────────────────────────────────────────────
        AttributeDefinition(
            name="branch_visit_preference",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.38,
            description="Preference for resolving banking needs in-person at a branch over digital alternatives.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="multi_bank_account_tendency",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.41,
            description="Tendency to spread finances across multiple banking institutions for different purposes.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="overdraft_comfort",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.28,
            description="Comfort using overdraft facilities as a short-term cash management tool.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="contactless_payment_adoption",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.65,
            description="Frequency of using contactless or mobile payment methods over cash or chip-and-pin.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="savings_discipline",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.50,
            description="Consistency in setting aside savings from income, independent of income level.",
            is_anchor=False,
        ),
        # ── investment attitudes ──────────────────────────────────────────
        AttributeDefinition(
            name="passive_investing_preference",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.45,
            description="Preference for passive index-tracking strategies over active stock picking or managed funds.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="esg_investment_weight",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.36,
            description="Weight given to environmental, social, and governance criteria when selecting investments.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="portfolio_diversification_priority",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.52,
            description="Priority placed on spreading investment risk across asset classes and geographies.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="market_volatility_anxiety",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.49,
            description="Anxiety level triggered by short-term market downturns that may lead to panic selling.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="robo_advisor_openness",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.38,
            description="Willingness to use algorithm-driven robo-advisors as a substitute for human financial advice.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="retirement_planning_urgency",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.44,
            description="Urgency placed on actively contributing to and managing retirement savings vehicles.",
            is_anchor=False,
        ),
        # ── insurance behaviour ───────────────────────────────────────────
        AttributeDefinition(
            name="insurance_coverage_breadth_preference",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.46,
            description="Preference for comprehensive coverage with higher premiums over minimal cover to reduce cost.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="insurance_claim_hesitancy",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.40,
            description="Reluctance to file insurance claims for fear of premium increases or policy implications.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="life_event_insurance_trigger",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.55,
            description="Tendency to review and update insurance coverage in response to major life events.",
            is_anchor=False,
        ),
        # ── credit behaviour ─────────────────────────────────────────────
        AttributeDefinition(
            name="credit_score_awareness",
            category="identity",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.43,
            description="Active awareness of personal credit score and the factors influencing it.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="buy_now_pay_later_adoption",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.34,
            description="Adoption of BNPL schemes as a routine payment method for purchases.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="mortgage_vs_rent_orientation",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.56,
            description="Orientation toward homeownership and mortgage commitment (1.0) versus preference for renting flexibility (0.0).",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="debt_aversion",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.55,
            description="Emotional and psychological aversion to carrying any form of personal debt.",
            is_anchor=False,
        ),
        # ── fintech engagement ────────────────────────────────────────────
        AttributeDefinition(
            name="fintech_early_adoption_tendency",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.31,
            description="Tendency to try new fintech apps and services before mainstream adoption.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="financial_app_engagement_frequency",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.48,
            description="Frequency of actively checking and using personal finance apps to track budgets and transactions.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="data_privacy_concern_financial",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.57,
            description="Concern about how financial institutions collect, store, and monetise personal data.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="peer_to_peer_transfer_comfort",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.53,
            description="Comfort using peer-to-peer payment platforms for splitting bills and personal transfers.",
            is_anchor=False,
        ),
        # ── financial decision style ──────────────────────────────────────
        AttributeDefinition(
            name="financial_goal_formality",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.39,
            description="Tendency to set written, structured financial goals rather than general aspirations.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="financial_news_consumption",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.36,
            description="Frequency of consuming financial news and market commentary to inform decisions.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="tax_optimisation_engagement",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.37,
            description="Proactive engagement in tax-efficient strategies, allowances, and wrappers.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="financial_product_switching_willingness",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.40,
            description="Willingness to switch financial providers when better rates or products are available.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="joint_financial_decision_preference",
            category="social",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.51,
            description="Preference for making major financial decisions jointly with a partner or household members.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="financial_stress_sensitivity",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.52,
            description="Degree to which financial uncertainty or debt generates significant psychological stress.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="inheritance_expectation_influence",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.22,
            description="Extent to which anticipated inheritance shapes current savings and investment decisions.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="preferred_banking_relationship_type",
            category="social",
            attr_type="categorical",
            options=["fully_digital", "hybrid", "relationship_banking"],
            population_prior=0.0,
            description="Preferred style of engagement with a primary banking provider.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="primary_investment_vehicle",
            category="decision_making",
            attr_type="categorical",
            options=["equities", "property", "bonds_fixed_income", "savings_accounts", "alternative_assets"],
            population_prior=0.0,
            description="Primary asset class or vehicle used to grow long-term wealth.",
            is_anchor=False,
        ),
    ]
)


__all__ = ["FINANCIAL_SERVICES_DOMAIN_ATTRIBUTES"]
