from __future__ import annotations

from src.taxonomy.base_taxonomy import AttributeDefinition


def _domain_attr_definitions(
    attrs: list[AttributeDefinition],
) -> list[AttributeDefinition]:
    # Goose’s filler relies on this marker + a `population_prior` dict.
    for a in attrs:
        setattr(a, "is_domain_specific", True)

        pp = getattr(a, "population_prior", None)
        if isinstance(pp, (int, float)):
            v = float(pp)
            if v > 0.66:
                label = "high"
            elif v > 0.33:
                label = "medium"
            else:
                label = "low"
            setattr(a, "population_prior", {"value": v, "label": label})
    return attrs


SAAS_DOMAIN_ATTRIBUTES: list[AttributeDefinition] = _domain_attr_definitions(
    [
        AttributeDefinition(
            name="free_trial_dependency",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.5,
            description="How strongly they expect a free trial before committing to a SaaS decision.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="proof_of_concept_requirement",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.43,
            description="Need for a structured proof of concept before full onboarding or rollout.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="demo_request_tendency",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.52,
            description="Tendency to request product demos to reduce uncertainty.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="solo_decision_authority",
            category="identity",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.42,
            description="How often they can make or finalize the decision without heavy committee review.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="procurement_process_tolerance",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.46,
            description="Comfort with procurement workflows, vendor paperwork, and process steps.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="committee_buy_in_need",
            category="social",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.47,
            description="How strongly they require alignment from multiple stakeholders before committing.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="ux_over_features_preference",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.45,
            description="Preference for usability and workflow experience over raw feature breadth.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="onboarding_patience",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.39,
            description="Patience for onboarding/setup steps before expecting productive value.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="feature_complexity_tolerance",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.4,
            description="Willingness to learn complex feature sets in exchange for power/control.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="integration_lock_in_sensitivity",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.48,
            description="Sensitivity to how integrations may increase future switching difficulty.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="data_migration_anxiety",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.44,
            description="Anxiety about migrating data, mapping schemas, and ensuring continuity.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="switching_cost_aversion",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.5,
            description="Aversion to disruption risk and cost if the company must switch vendors later.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="per_seat_preference",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.46,
            description="Preference for pricing models proportional to seats/users rather than usage alone.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="usage_based_comfort",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.34,
            description="Comfort with usage-based or metered pricing patterns.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="annual_commitment_willingness",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.41,
            description="Willingness to commit to annual contracts in exchange for discounts/predictability.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="scalability_concern",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.38,
            description="Concern that the SaaS product may not scale with growing workload/team size.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="enterprise_upgrade_aspiration",
            category="identity",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.33,
            description="Aspiration to move from starter plans to enterprise-grade capabilities.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="startup_tool_openness",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.39,
            description="Openness to adopting tools from newer startups rather than only incumbents.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="security_compliance_prioritisation",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.52,
            description="Prioritization of security posture and compliance artifacts during vendor evaluation.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="data_sovereignty_concern",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.36,
            description="Concern about where customer data is stored/processed and related governance.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="audit_trail_need",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.43,
            description="Need for logs/audit trails for compliance, investigation, and accountability.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="vendor_trust_sensitivity",
            category="social",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.46,
            description="Sensitivity to vendor credibility, reputation, and reliability.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="sales_rep_influence",
            category="social",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.34,
            description="How much salesperson persuasion affects evaluation outcomes.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="csm_engagement_preference",
            category="social",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.35,
            description="Preference for proactive customer success management and structured check-ins.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="sla_requirement_tendency",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.45,
            description="Tendency to require clear SLAs/uptime guarantees as part of procurement.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="incident_response_expectation",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.37,
            description="Expectation that vendors have mature incident response and escalation processes.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="support_channel_preference",
            category="lifestyle",
            attr_type="categorical",
            options=["self_serve", "email", "chat", "phone"],
            population_prior=0.0,
            description="Preferred support channel for resolving SaaS issues.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="documentation_sufficiency_preference",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.42,
            description="Preference for thorough docs, runbooks, and knowledge bases.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="training_requirement_level",
            category="lifestyle",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.35,
            description="How much internal training they expect before full adoption.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="compliance_vendor_docs_reads",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.3,
            description="Tendency to actually read security/compliance documentation rather than trusting summaries.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="open_api_preference",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.47,
            description="Preference for API-first extensibility over closed integrations.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="integration_partner_preference",
            category="decision_making",
            attr_type="categorical",
            options=["native_integrations", "third_party_marketplace", "custom_build"],
            population_prior=0.0,
            description="Preferred integration path when selecting a SaaS stack.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="risk_management_approval_steps",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.44,
            description="Likelihood to require security/risk approvals and staged sign-offs.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="vendor_lockin_regret",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.4,
            description="How much they anticipate regret about future inability to switch vendors.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="migration_timeline_comfort",
            category="decision_making",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.43,
            description="Comfort with longer migration timelines if it reduces disruption risk.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="time_to_value_requirement",
            category="identity",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.48,
            description="How strongly they demand value quickly after purchase.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="tool_sprawl_tolerance",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.36,
            description="Tolerance for adding more tools to the stack rather than consolidating.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="change_resistance",
            category="psychology",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.42,
            description="Resistance to changes in workflows and processes that SaaS adoption requires.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="internal_tooling_customization_need",
            category="identity",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.34,
            description="Need to customize the tool (roles, workflows, templates) to fit internal processes.",
            is_anchor=False,
        ),
        AttributeDefinition(
            name="dashboard_over_raw_data_preference",
            category="values",
            attr_type="continuous",
            range_min=0.0,
            range_max=1.0,
            population_prior=0.31,
            description="Preference for dashboards and summarized insights over raw exports and manual analysis.",
            is_anchor=False,
        ),
    ]
)


__all__ = ["SAAS_DOMAIN_ATTRIBUTES"]
