/**
 * LivePersonaWall — full-bleed hero background of real persona portraits
 * generated by users earlier in the week.
 *
 * Pulls /community/personas, filters to ones with portrait_url, distributes
 * them across 5 columns that drift vertically at different speeds. Black
 * gradient overlay keeps the foreground heading readable.
 *
 * Click any portrait to land on that persona's public detail page.
 */
"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { API } from "@/lib/api";

interface CommunityPersona {
  persona_id: string;
  name: string;
  age: number;
  city: string;
  country: string;
  portrait_url: string | null;
  snippet: string;
}

const COL_COUNT = 5;
// Per-column drift speeds (seconds for one full loop). Different durations
// create a gentle parallax — the eye keeps finding new faces.
const COL_DURATIONS = [62, 78, 54, 86, 70];
// Reverse direction for alternating columns to avoid uniform downward feel.
const COL_DIRS = [1, -1, 1, -1, 1];

export default function LivePersonaWall() {
  const [personas, setPersonas] = useState<CommunityPersona[]>([]);
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    let cancelled = false;
    // Same-origin proxy with 60s cache — see app/api/community/personas/route.ts
    fetch(`/api/community/personas?limit=60`)
      .then((r) => (r.ok ? r.json() : []))
      .then((rows: CommunityPersona[]) => {
        if (cancelled) return;
        const withPortrait = rows.filter((r) => !!r.portrait_url);
        setPersonas(withPortrait);
        setLoaded(true);
      })
      .catch(() => setLoaded(true));
    return () => {
      cancelled = true;
    };
  }, []);

  // Build per-column lists. We want each column densely populated so the
  // loop never reveals empty space. Repeat the source list until we have
  // ~10 tiles per column, then duplicate again so the CSS loop is seamless.
  const columns = buildColumns(personas, COL_COUNT);

  return (
    <div
      aria-hidden={personas.length === 0}
      className="absolute inset-0 overflow-hidden"
      style={{ pointerEvents: personas.length === 0 ? "none" : "auto" }}
    >
      <style>{`
        @keyframes wallDriftDown {
          0%   { transform: translate3d(0, -50%, 0); }
          100% { transform: translate3d(0, 0, 0); }
        }
        @keyframes wallDriftUp {
          0%   { transform: translate3d(0, 0, 0); }
          100% { transform: translate3d(0, -50%, 0); }
        }
        @media (prefers-reduced-motion: reduce) {
          .wall-col { animation: none !important; }
        }
      `}</style>

      <div className="absolute inset-0 grid" style={{
        gridTemplateColumns: `repeat(${COL_COUNT}, 1fr)`,
        gap: "12px",
        padding: "12px",
      }}>
        {columns.map((col, ci) => (
          <div
            key={ci}
            className="wall-col"
            style={{
              animation: `${COL_DIRS[ci] === 1 ? "wallDriftDown" : "wallDriftUp"} ${COL_DURATIONS[ci]}s linear infinite`,
              willChange: "transform",
            }}
          >
            {col.map((p, ti) => (
              <PortraitTile key={`${ci}-${ti}-${p.persona_id}`} p={p} />
            ))}
          </div>
        ))}
      </div>

      {/* Foreground readability gradient — top→bottom only so the wall
          stays edge-to-edge horizontally. */}
      <div
        aria-hidden="true"
        className="absolute inset-0 pointer-events-none"
        style={{
          background:
            "linear-gradient(180deg, rgba(5,5,5,0.30) 0%, rgba(5,5,5,0.55) 45%, rgba(5,5,5,0.92) 100%)",
        }}
      />

      {/* Empty/loading fallback so hero never looks broken */}
      {loaded && personas.length === 0 && (
        <div
          aria-hidden="true"
          className="absolute inset-0"
          style={{
            backgroundImage:
              "linear-gradient(rgba(233,230,223,0.022) 1px, transparent 1px), linear-gradient(90deg, rgba(233,230,223,0.022) 1px, transparent 1px)",
            backgroundSize: "72px 72px",
          }}
        />
      )}
    </div>
  );
}

function PortraitTile({ p }: { p: CommunityPersona }) {
  const place = [p.city, p.country].filter(Boolean).join(", ");
  return (
    <Link
      href={`/persona/${p.persona_id}`}
      className="group relative block mb-3 overflow-hidden border border-parchment/5 hover:border-signal/40 transition-colors"
      style={{ aspectRatio: "3 / 4" }}
      title={`${p.name}${p.age ? `, ${p.age}` : ""}${place ? ` · ${place}` : ""}`}
    >
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={p.portrait_url ?? ""}
        alt=""
        loading="lazy"
        decoding="async"
        className="absolute inset-0 w-full h-full object-cover opacity-70 group-hover:opacity-100 transition-opacity duration-500"
      />
      <div
        className="absolute inset-x-0 bottom-0 px-2 py-2 opacity-0 group-hover:opacity-100 transition-opacity"
        style={{ background: "linear-gradient(0deg, rgba(5,5,5,0.92), transparent)" }}
      >
        <div className="font-condensed font-bold text-parchment text-xs leading-tight truncate">
          {p.name}
          {p.age ? <span className="text-parchment/60">, {p.age}</span> : null}
        </div>
        {place && (
          <div className="font-mono text-[9px] text-static tracking-widest uppercase truncate">
            {place}
          </div>
        )}
      </div>
    </Link>
  );
}

function buildColumns(personas: CommunityPersona[], cols: number) {
  if (personas.length === 0) {
    return Array.from({ length: cols }, () => [] as CommunityPersona[]);
  }
  // Round-robin so adjacent tiles in a column come from spread positions
  // in the source list — keeps neighbouring columns visually distinct.
  const buckets: CommunityPersona[][] = Array.from({ length: cols }, () => []);
  personas.forEach((p, i) => {
    buckets[i % cols].push(p);
  });
  // Pad each column to >=10 tiles by repeating, then duplicate so the
  // -50% → 0 loop seam is invisible.
  return buckets.map((b) => {
    if (b.length === 0) return [];
    const out: CommunityPersona[] = [];
    let i = 0;
    while (out.length < 10) {
      out.push(b[i % b.length]);
      i += 1;
    }
    return [...out, ...out];
  });
}
